services:
  app:
    build: .
    environment:
      - PORT=8000
      - USE_SQLITE=False
      - DB_NAME=forex_db
      - DB_USER=postgres
      - DB_PASSWORD=MonMotDePasseFort2026!
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - USE_REDIS=True
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: forex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MonMotDePasseFort2026!
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d forex_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  celery_worker:
    build: .
    command: sh -c "cd /app/forex_platform && celery -A forex_platform worker --loglevel=info"
    environment:
      - USE_SQLITE=False
      - DB_NAME=forex_db
      - DB_USER=postgres
      - DB_PASSWORD=MonMotDePasseFort2026!
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - USE_REDIS=True
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always

  celery_beat:
    build: .
    command: sh -c "cd /app/forex_platform && celery -A forex_platform beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    environment:
      - USE_SQLITE=False
      - DB_NAME=forex_db
      - DB_USER=postgres
      - DB_PASSWORD=MonMotDePasseFort2026!
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - USE_REDIS=True
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: always

  flower:
    build: .
    command: sh -c "cd /app/forex_platform && celery -A forex_platform flower --port=5555"
    environment:
      - USE_SQLITE=False
      - DB_NAME=forex_db
      - DB_USER=postgres
      - DB_PASSWORD=MonMotDePasseFort2026!
      - DB_HOST=db
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - celery_worker
    restart: always

volumes:
  postgres_data_v2:
